/* ASI CREAMOS LA DB EN MYSQL O SE PUEDE DESDE MYSQL WORKBENCH */


/* CREATE TABLE mediciones (
  fecha VARCHAR(45) NOT NULL,
  origen VARCHAR(100) NOT NULL,
  valor INTEGER(10) NOT NULL,
  codigoSensor VARCHAR(100) PRIMARY KEY NOT NULL,
  observacion VARCHAR(100) NOT NULL,
  imagen VARCHAR(200) NOT NULL
) */